"""Initial migration.

Revision ID: baf0c8b4b57f
Revises: 
Create Date: 2024-06-12 09:58:51.457984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf0c8b4b57f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('participants', sa.Integer(), nullable=False),
    sa.Column('winner', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race')
    # ### end Alembic commands ###
